username = 'Никита Зайцев'
print(username)
title='Заметки'
print(title)
content=('описание заметки')
print(content)
status=('статус заметки')
print(status)
created_date=('17-12-2024')
print(created_date)
created_date=('17.12')
print(created_date)
issue_date=('17-01-2025')
print(issue_date)
issue_date=('17.01')
print(issue_date)
